include:
  - board: seeeduino_xiao_ble
    shield: totem_left 
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_display
    snippet: zmk-usb-logging


  
# there is no settingsreset (needed) for the XIAO
